# Generated by Django 4.2.5 on 2025-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerifyCodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verify_code", models.CharField(max_length=5, unique=True)),
                ("life_time", models.DateTimeField(null=True)),
                ("type", models.CharField(max_length=20)),
                ("user_email", models.CharField(max_length=255)),
                ("dop_info", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "verify_code",
                "verbose_name_plural": "verify_codes",
                "db_table": "verify_code",
            },
        ),
    ]
