version: '3.8'

x-mariami-api-common-dev: &mariami-api-common-dev
    env_file:
        - .env
    entrypoint: scripts/entrypoint.sh
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/mariami
    networks:
        - mariami-network-dev
    depends_on:
        mariami-db-dev:
            condition: service_healthy
        mariami-redis-dev:
            condition: service_healthy

services:
    mariami-db-dev:
        container_name: mariami-db-dev
        env_file:
            - .env
        image: postgres:latest
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - mariami-network-dev
        healthcheck:
            test: pg_isready -U postgres -d postgres
            timeout: 5s
            retries: 20

    mariami-redis-dev:
        container_name: mariami-redis-dev
        env_file:
            - .env
        image: redis:7.0.4-alpine
        volumes:
            - redis-data:/usr/src/mariami/storage/redis/data
        networks:
            - mariami-network-dev
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            timeout: 5s
            retries: 20

    mariami-api-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-api-dev
        command: api
        ports:
            - 8000:8000

    mariami-daphne-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-daphne-dev
        command: daphne
        ports:
            - 10000:10000

    mariami-celery-worker-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-celery-worker-dev
        command: celery-worker

    mariami-celery-beat-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-celery-beat-dev
        command: celery-beat

    mariami-pgadmin-dev:
        container_name: mariami-pgadmin-dev
        env_file:
            - .env
        image: dpage/pgadmin4:latest
        restart: always
        volumes:
            - pgadmin-data:/usr/src/mariami/storage/pgadmin/data
        networks:
            - mariami-network-dev
        ports:
            - 49280:49299

networks:
    mariami-network-dev:
        name: mariami-network-dev

volumes:
    redis-data:
    minio-data:
    pgadmin-data:
