version: '3.8'

x-mariami-api-common-prod: &mariami-api-common-prod
    env_file:
        - .env.prod
    entrypoint: scripts/entrypoint.sh
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/mariami
    networks:
        - mariami_server
    depends_on:
        mariami-db-prod:
            condition: service_healthy
        mariami-redis-prod:
            condition: service_healthy
        mariami-minio-prod:
            condition: service_healthy

services:

    mariami-db-prod:
        container_name: mariami-db-prod
        env_file:
            - .env.prod
        image: postgres:17-alpine
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - mariami_server
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            timeout: 5s
            retries: 20

    mariami-redis-prod:
        container_name: mariami-redis-prod
        env_file:
            - .env.prod
        image: redis:7.0.4-alpine
        volumes:
            - redis-data:/usr/src/mariami/storage/redis/data
        networks:
            - mariami_server
        healthcheck:
            test: [ 'CMD-SHELL', 'redis-cli ping | grep PONG' ]
            timeout: 5s
            retries: 20

    mariami-api-prod:
        <<: *mariami-api-common-prod
        container_name: mariami-api-prod
        command: api-deploy
        expose:
            - '8000'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.mariami-api-prod.rule=Host(`api.finclai.com`)'
            - 'traefik.http.routers.mariami-api-prod.entrypoints=websecure'
            - 'traefik.http.routers.mariami-api-prod.tls.certresolver=myresolver'
            - 'traefik.http.routers.mariami-api-prod.service=mariami-api-prod'
            - 'traefik.http.services.mariami-api-prod.loadbalancer.server.port=8000'

    mariami-celery-worker-prod:
        <<: *mariami-api-common-prod
        container_name: mariami-celery-worker-prod
        command: celery-worker

    mariami-celery-beat-prod:
        <<: *mariami-api-common-prod
        container_name: mariami-celery-beat-prod
        command: celery-beat

    mariami-minio-prod:
        container_name: mariami-minio-prod
        image: minio/minio:RELEASE.2021-10-23T03-28-24Z
        env_file:
            - .env.prod
        command: server /data --console-address ":9001"
        volumes:
            - minio-data:/data
        networks:
            - mariami_server
        expose:
            - "9000"
            - "9001"
        labels:
            - 'traefik.enable=true'
            # Console
            - 'traefik.http.routers.minio-console.rule=Host(`storage-console.finclai.com`)'
            - 'traefik.http.routers.minio-console.entrypoints=websecure'
            - 'traefik.http.routers.minio-console.tls.certresolver=myresolver'
            - 'traefik.http.routers.minio-console.service=minio-console'
            - 'traefik.http.services.minio-console.loadbalancer.server.port=9001'
            # APi
            - 'traefik.http.routers.mariami-minio-prod.rule=Host(`storage.finclai.com`)'
            - 'traefik.http.routers.mariami-minio-prod.entrypoints=websecure'
            - 'traefik.http.routers.mariami-minio-prod.tls.certresolver=myresolver'
            - 'traefik.http.routers.mariami-minio-prod.service=mariami-minio-prod'
            - 'traefik.http.services.mariami-minio-prod.loadbalancer.server.port=9000'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

networks:
    mariami_server:
        external: true

volumes:
    redis-data:
    minio-data:
    pgadmin-data:
