version: '3.8'

x-mariami-api-common-dev: &mariami-api-common-dev
    env_file:
        - .env
    entrypoint: scripts/entrypoint.sh
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/mariami
    networks:
        - mariami-network-dev
    depends_on:
        mariami-db-dev:
            condition: service_healthy
        mariami-redis-dev:
            condition: service_healthy
        mariami-minio-dev:
            condition: service_healthy

services:
    mariami-db-dev:
        container_name: mariami-db-dev
        env_file:
            - .env
        image: postgres:latest
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - mariami-network-dev
        healthcheck:
            test: pg_isready -U postgres -d postgres
            timeout: 5s
            retries: 20

    mariami-redis-dev:
        container_name: mariami-redis-dev
        env_file:
            - .env
        image: redis:7.0.4-alpine
        volumes:
            - redis-data:/usr/src/mariami/storage/redis/data
        networks:
            - mariami-network-dev
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            timeout: 5s
            retries: 20

    mariami-api-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-api-dev
        command: api
        ports:
            - 8000:8000

    mariami-daphne-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-daphne-dev
        command: daphne
        ports:
            - 10000:10000

    mariami-celery-worker-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-celery-worker-dev
        command: celery-worker

    mariami-celery-beat-dev:
        <<: *mariami-api-common-dev
        container_name: mariami-celery-beat-dev
        command: celery-beat

    mariami-pgadmin-dev:
        container_name: mariami-pgadmin-dev
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@gmail.com
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_LISTEN_PORT: 49299
          PGADMIN_CONFIG_SERVER_MODE: 'False'
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
        image: dpage/pgadmin4:latest
        restart: always
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
            - ./pgadmin/pgpass:/pgpass:ro
        networks:
            - mariami-network-dev
        ports:
            - 49280:49299
        depends_on:
            - mariami-db-dev

    mariami-minio-dev:
        container_name: mariami-minio-dev
        image: minio/minio:RELEASE.2021-10-23T03-28-24Z
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
        command: server /data --console-address ":9001"
        volumes:
            - ./local-data/minio:/data
        networks:
            - mariami-network-dev
        ports:
            - "9000:9000"
            - "9001:9001"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    mariami-minio-init-dev:
        container_name: mariami-minio-init-dev
        image: minio/mc:latest
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
        volumes:
            - ./scripts/init-minio.sh:/init-minio.sh:ro
            - ./project/templates/user_data:/templates:ro
            - ./project/docs:/docs:ro
        networks:
            - mariami-network-dev
        depends_on:
            mariami-minio-dev:
                condition: service_healthy
        entrypoint: /bin/bash
        command: ["/init-minio.sh"]
        restart: "no"

networks:
    mariami-network-dev:
        name: mariami-network-dev

volumes:
    redis-data:
    minio-data:
    pgadmin-data:
    postgres-data:
