# Generated by Django 4.2.4 on 2023-09-15 08:46

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("win_chance", models.JSONField()),
                (
                    "balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "USD $")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=14,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("winning", "Winning"), ("losing", "Losing")],
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "user",
                "ordering": ["-id"],
            },
        ),
    ]
