# Generated by Django 4.2.5 on 2025-10-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="profile.profilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "user",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserDataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("pnl_template", "Pnl Template"),
                            ("transactions_template", "Transactions Template"),
                            ("invoices_template", "Invoices Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveIntegerField()),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata for the file (e.g., PnL column configurations)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_data_files",
                "indexes": [
                    models.Index(
                        fields=["user", "template_type"],
                        name="user_data_f_user_id_a3937b_idx",
                    ),
                    models.Index(
                        fields=["upload_time"], name="user_data_f_upload__a4e0bd_idx"
                    ),
                ],
                "unique_together": {("user", "template_type", "is_active")},
            },
        ),
    ]
