# Generated by Django 4.2.4 on 2023-09-28 12:29

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usermodel_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="total_depsosit_sum",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=9,
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="total_depsosit_sum_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "USD $")], default="USD", editable=False, max_length=3
            ),
        ),
    ]
