# Generated by Django 4.2.5 on 2025-09-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
        ("users", "0002_alter_usermodel_last_name_alter_usermodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="country",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="name",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="profile.profilemodel",
            ),
        ),
    ]
