# Generated by Django 4.2.5 on 2023-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usermodel_total_depsosit_sum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
