# Generated by Django 4.2.5 on 2023-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usermodel_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="time_started_winnin_account_after_deposit",
            field=models.DateTimeField(null=True),
        ),
    ]
