# Generated by Django 4.2.5 on 2025-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("employees_count", models.PositiveIntegerField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "fiscal_year_start",
                    models.DateField(
                        blank=True, help_text="Fiscal year start date", null=True
                    ),
                ),
                (
                    "update_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "primary_focus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("profit", "Profit"),
                            ("growth", "Growth"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "business_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("multicurrency", models.BooleanField(default=False)),
                (
                    "capital_reserve_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profile",
            },
        ),
    ]
