# Generated by Django 4.2.5 on 2025-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="business_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="capital_reserve_target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="fiscal_year_start",
            field=models.CharField(
                blank=True,
                help_text="MM-DD format, e.g., 01-01",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="multicurrency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="primary_focus",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("profit", "Profit"), ("growth", "Growth")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="update_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
