# Generated by Django 4.2.5 on 2025-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="ai_insight",
            field=models.TextField(
                blank=True,
                help_text="AI-generated business insight based on profile data",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="company_info",
            field=models.TextField(
                blank=True, help_text="Detailed description of the business", null=True
            ),
        ),
    ]
