# Generated by Django 4.2.5 on 2025-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_profilemodel_business_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="fiscal_year_start",
            field=models.DateField(
                blank=True, help_text="Fiscal year start date", null=True
            ),
        ),
    ]
